### ISSUE TITLE
Adding Feature: Ignore URL Patterns

### ISSUE THREAD

**Issue by sonechca** [IcemanEtika/deadlinkz#6]
Hi,

I would like to add a new feature " Ignore URL patterns" for lab 4.
I think your code is well organized and readable.
Can I add the new feature to your code?
Thank you

**Comment by IcemanEtika** [comment]
Yeah sure, go for it.

If you haven't had that feature added to yours yet I'd also be willing to do it for you. Might not be able to start on it until Thursday or Friday because I'm pretty busy with stuff atm so let me know if that's alright with you.

**Comment by sonechca** [comment]
Hi,

You can take your time :)
I uploaded a new feature, Can you check PR?
Thank you
